// Delta: packaging fix for META-INF NOTICE/LICENSE collisions (merge into your existing block if needed)
android {
    packaging {
        resources {
            pickFirsts += [
                "META-INF/NOTICE.md",
                "META-INF/LICENSE.md",
                "META-INF/DEPENDENCIES",
                "META-INF/NOTICE",
                "META-INF/LICENSE"
            ]
        }
    }
}
