name: Android CI (Release)

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-35
            build-tools;35.0.0
            platform-tools

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release
        run: ./gradlew --no-daemon assembleRelease
